title: "Eran Meshorer Lab"
description: "Epigenetics, Stem Cells, and Neurons"
baseurl: ""
url: ""

markdown: kramdown

plugins:
  - jekyll-feed

defaults:
  - scope:
      path: ""
    values:
      layout: home
